# -*- coding: utf-8 -*-
"""Simulation des capteurs

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Ot78oBnXkt3ZiCEutPsLBpEu3mmLIpvc
"""

pip install git+https://github.com/ozgur/python-firebase

from firebase import firebase
import time
import random
from datetime import datetime

url = 'https://iotapp-ae6e4-default-rtdb.firebaseio.com/'
firebase = firebase.FirebaseApplication(url)
while True:
    now = datetime.now()
    timeNow = now.strftime("%Y/%m/%d %H:%M:%S")
    cTemp = random.randint(35,38)
    Tension = random.randint(10,14)
    Card = random.randint(55,85)
    data={'Température': str(cTemp),'Tension':str(Tension), 'frequence cardiaque':str(Card)}
    result = firebase.post(timeNow, data)
    time.sleep(20)