# Generated by Django 4.0.2 on 2022-02-08 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Messages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Message', models.CharField(max_length=1000)),
                ('idDestinataire', models.CharField(max_length=100)),
                ('idEmetteur', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Médecins',
            fields=[
                ('MédecinId', models.AutoField(primary_key=True, serialize=False)),
                ('MédecinName', models.CharField(max_length=100)),
                ('MédecinAge', models.CharField(max_length=100)),
                ('MédecinCin', models.CharField(max_length=100)),
                ('Hospital', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('PatientId', models.AutoField(primary_key=True, serialize=False)),
                ('PatientName', models.CharField(max_length=100)),
                ('PatientAge', models.CharField(max_length=100)),
                ('PatientAdress', models.CharField(max_length=100)),
                ('PatientCin', models.CharField(max_length=100)),
                ('idMédecin', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tuteurs',
            fields=[
                ('TuteurId', models.AutoField(primary_key=True, serialize=False)),
                ('TuteurName', models.CharField(max_length=100)),
                ('TuteurAge', models.CharField(max_length=100)),
                ('TuteurCin', models.CharField(max_length=100)),
                ('TuteurAdress', models.CharField(max_length=100)),
                ('TuteurNum', models.CharField(max_length=100)),
                ('idPatient', models.CharField(max_length=100)),
            ],
        ),
    ]
